#!/usr/bin/env bash
#
# migrate-to-xdg.sh
#
# Move ccvalet's data out of the legacy ~/.ccvalet/ directory and into the
# XDG-compliant locations used by current versions:
#
#   config:  $XDG_CONFIG_HOME/honjin   (default ~/.config/honjin)
#   state:   $XDG_STATE_HOME/honjin    (default ~/.local/state/honjin)
#   socket:  $XDG_RUNTIME_DIR/honjin   (regenerated automatically)
#
# Safe to re-run: refuses to clobber existing files in the target directories.
# Run with --dry-run to preview without touching anything.

set -euo pipefail

OLD_DIR="${HOME}/.ccvalet"
CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/honjin"
STATE_DIR="${XDG_STATE_HOME:-${HOME}/.local/state}/honjin"

DRY_RUN=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [--dry-run]

Migrate legacy ~/.ccvalet/ data into XDG Base Directory locations.

Options:
  -n, --dry-run   Print what would happen without making changes.
  -h, --help      Show this help.
EOF
}

for arg in "$@"; do
  case "$arg" in
    -n|--dry-run) DRY_RUN=1 ;;
    -h|--help)    usage; exit 0 ;;
    *) echo "Error: unknown option: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

say() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run] %s\n' "$*"
  else
    printf '%s\n' "$*"
  fi
}

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run] $ %s\n' "$*"
  else
    "$@"
  fi
}

# Pre-flight: nothing to do?
if [ ! -d "$OLD_DIR" ]; then
  echo "No legacy directory at $OLD_DIR — nothing to migrate."
  exit 0
fi

# Pre-flight: if a legacy daemon is still running, stop it.
# Reason: post-XDG `jin daemon stop` looks at the new socket path and
# cannot see a legacy daemon listening on the old socket, so we have to
# terminate it ourselves before moving files.
stop_legacy_daemon() {
  local legacy_sock="$OLD_DIR/run/daemon.sock"
  [ -S "$legacy_sock" ] || return 0

  echo "Detected legacy daemon socket: $legacy_sock"

  local pids
  # Match `ccvalet daemon` and `ccvalet daemon start` (and any variants started
  # with explicit subcommand). Strict enough to avoid catching `ccvalet ui`,
  # `ccvalet session ...`, etc. `-u $(id -u)` restricts to processes owned by
  # the current user so we don't try to signal another user's ccvalet.
  pids=$(pgrep -u "$(id -u)" -f 'ccvalet[[:space:]]+daemon([[:space:]]|$)' 2>/dev/null || true)

  if [ -z "$pids" ]; then
    say "No live ccvalet daemon process found; removing stale socket only."
    run rm -f "$legacy_sock"
    return 0
  fi

  echo "Sending SIGTERM to legacy daemon process(es): $(echo "$pids" | tr '\n' ' ')"
  if [ "$DRY_RUN" -eq 1 ]; then
    say "would: kill -TERM $pids"
    return 0
  fi

  # shellcheck disable=SC2086
  kill -TERM $pids 2>/dev/null || true

  local i
  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    [ -S "$legacy_sock" ] || break
    sleep 0.2
  done

  if [ -S "$legacy_sock" ]; then
    echo "Daemon did not exit after 3s, sending SIGKILL"
    # shellcheck disable=SC2086
    kill -KILL $pids 2>/dev/null || true
    sleep 0.5
    rm -f "$legacy_sock"
  fi
}

stop_legacy_daemon

# Items to migrate: parallel arrays so paths containing spaces are safe.
move_rels=(
  config.yaml
  state.yaml
  sessions
  daemon-debug.log
  hook-debug.log
)
move_dests=(
  "$CONFIG_DIR"
  "$STATE_DIR"
  "$STATE_DIR"
  "$STATE_DIR"
  "$STATE_DIR"
)

# Items to drop instead of move. These are regenerated by the new binary on
# next startup and may even embed stale paths (e.g. an old execPath baked into
# hooks-settings.json), so keeping them around is worse than removing them.
drop_rels=(
  hooks-settings.json
)

# Detect conflicts up-front so we either fully apply or do nothing.
conflicts=()
planned=()
for i in "${!move_rels[@]}"; do
  rel="${move_rels[$i]}"
  dest_dir="${move_dests[$i]}"
  src="$OLD_DIR/$rel"
  dest="$dest_dir/$rel"
  [ -e "$src" ] || continue
  if [ -e "$dest" ]; then
    conflicts+=("$dest (source: $src)")
  else
    planned+=("$src -> $dest")
  fi
done

if [ "${#conflicts[@]}" -gt 0 ]; then
  {
    echo "Error: the following target paths already exist; refusing to overwrite:"
    for c in "${conflicts[@]}"; do
      echo "  $c"
    done
    echo
    echo "Move or delete those targets and re-run."
  } >&2
  exit 1
fi

if [ "${#planned[@]}" -eq 0 ]; then
  echo "Nothing to move. Legacy directory contains no recognized files."
  # Still try to clean up an empty legacy dir below.
else
  echo "Will migrate ${#planned[@]} item(s):"
  for p in "${planned[@]}"; do
    echo "  $p"
  done
fi

run mkdir -p "$CONFIG_DIR" "$STATE_DIR"

for i in "${!move_rels[@]}"; do
  rel="${move_rels[$i]}"
  dest_dir="${move_dests[$i]}"
  src="$OLD_DIR/$rel"
  [ -e "$src" ] || continue
  say "moving $src -> $dest_dir/"
  run mv "$src" "$dest_dir/"
done

# Drop derived files that the daemon regenerates on next startup.
for rel in "${drop_rels[@]}"; do
  src="$OLD_DIR/$rel"
  [ -e "$src" ] || continue
  say "removing derived file $src (regenerated on next daemon start)"
  run rm -f "$src"
done

# Drop the obsolete run/ directory (socket is regenerated on next daemon start).
if [ -d "$OLD_DIR/run" ]; then
  say "removing obsolete $OLD_DIR/run/"
  run rm -rf "$OLD_DIR/run"
fi

# Remove the legacy dir only if it is now empty; otherwise leave it for the user.
if [ -d "$OLD_DIR" ]; then
  if [ -z "$(ls -A "$OLD_DIR" 2>/dev/null)" ]; then
    say "removing empty $OLD_DIR"
    run rmdir "$OLD_DIR"
  else
    echo "Note: $OLD_DIR still contains files not recognized by this script:"
    ls -A "$OLD_DIR" | sed 's/^/  /'
    echo "Inspect and remove manually if no longer needed."
  fi
fi

if [ "$DRY_RUN" -eq 1 ]; then
  echo
  echo "Dry run complete. Re-run without --dry-run to apply."
else
  echo
  echo "Migration complete."
  echo "  Config:  $CONFIG_DIR"
  echo "  State:   $STATE_DIR"
fi
